# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-15 02:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('use', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dest', models.CharField(max_length=20)),
                ('start_date', models.DateField(default='')),
                ('end_date', models.DateField(default='')),
                ('cost', models.IntegerField(null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='tour_img')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ManyToManyField(blank=True, default='', null=True, to='use.customer')),
            ],
        ),
        migrations.CreateModel(
            name='TourInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourinfo', to='use.Tour')),
            ],
        ),
    ]
