# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-15 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('use', '0002_tour_tourinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_company',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_customer',
        ),
    ]
