# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-15 20:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('use', '0003_auto_20190215_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
